parameters:
  - name: stageName
    displayName: The name of the stage, defaults to check_hosts_online
    type: string
    default: check_hosts_online
  - name: dependencies
    displayName: A stage name or list of stage names this stage should depend on.
    type: object
    default: []
  - name: agentImage
    displayName: The image to use from the Microsoft Hosted agent pool.
    type: string
    default: ubuntu-latest
  - name: keyVaultName
    displayName: The name of the Azure KeyVault that contains the secrets required to connect to Twingate.
    type: string
  - name: serviceKeySecretName
    displayName: The name of the secret within the Azure KeyVault that contains the service key required to connect to Twingate.
    type: string
  - name: serviceConnection
    displayName: The service connection to use to authenticate to Azure CLI.
    type: string
  - name: hosts
    displayName: List of objects with a name and an address property to check if hosts are powered on and can received traffic.
    type: object

stages:
  - stage: ${{ parameters.stageName }}
    dependsOn: ${{ parameters.dependencies }}
    jobs:
      - job: ${{ parameters.stageName }}
        pool:
          vmImage: ${{ parameters.agentImage }}
        steps:
          - template: ../steps/twingate-connect.yaml
            parameters:
              keyVaultName: ${{ parameters.keyVaultName }}
              serviceKeySecretName: ${{ parameters.serviceKeySecretName }}
              serviceConnection: ${{ parameters.serviceConnection }}
          - template: ../steps/check-hosts-online.yaml
            parameters:
              hosts: ${{ parameters.hosts }}
