name: YAML Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '**.yaml'
      - '**.yml'
      - '.github/workflows/yaml-lint.yml'

jobs:
  yaml-lint:
    name: Lint YAML Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install yamllint
        run: |
          pip install yamllint

      - name: Run yamllint
        run: |
          yamllint -f parsable -c .yamllint.yml .
